import { Header } from "../src/components/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-primary text-white" suppressHydrationWarning={true}>
        <Header />
        {children}
      </body>
    </html>
  );
}
