import { Header } from '@j4j/components';
import './globals.css';
import { Inter } from 'next/font/google';
import { HeadLine } from '@/components/activitiesHeadlines/HeadLine';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <HeadLine />
        {children}
      </body>
    </html>
  );
}
